# Generated by Django 3.2.3 on 2021-05-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaClone', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['pub_date']},
        ),
    ]
