# Generated by Django 3.2.3 on 2021-05-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaClone', '0009_alter_image_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
